services:
  cinerate-web-api-server:
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ${HOME}/.aws:/root/.aws:ro
      - ${HOME}/.creds:/root/.creds:ro
    command: npm start

  cinerate-web-db:
    restart: always
    env_file:
      - .env
