services:
  express-api-server:
    container_name: express-api-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    environment:
      - SERVER_PORT=${SERVER_PORT:-3000}
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: ${VOLUME_NAME:-mrw-db-data}
