services:
  cinerate-web-api-server:
    build:
      target: build
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@cinerate-web-db:5432/${POSTGRES_DB:-app}?schema=public
      - AWS_PROFILE=${AWS_PROFILE}
      - S3_BUCKET=cinerate-movie-review-service
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.creds/cinerate-firebase-adminsdk.json
    ports:
      - 9229:9229
    volumes:
      - .:/app
      - ${HOME}/.aws:/root/.aws:ro
      - ${HOME}/.creds:/root/.creds:ro
      - /app/node_modules
    command: npm run debug

  cinerate-web-db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - POSTGRES_DB=${POSTGRES_DB:-app}
