services:
  api-server:
    build:
      target: build
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@postgres-db:5432/${POSTGRES_DB:-app}?schema=public
      - JWT_SECRET=${JWT_SECRET:-5snACD6WbVNXQGq8iZC6kVJFc}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  postgres-db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - POSTGRES_DB=${POSTGRES_DB:-app}
