services:
  server:
    container_name: server
    depends_on:
      - postgres-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}

  postgres-db:
    container_name: postgres-db
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: ${VOLUME_NAME:-mra-db-data}
