services:
  server:
    build:
      target: build
    environment:
      - DATABASE_URL=postgresql://app:app@postgres-db:5432/app?schema=public
      - SERVER_PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm run migrate-dev && npm run dev"

  postgres-db:
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
