name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use latest Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run ci-lint
      - name: Check code formatting
        run: npm run format-check
